const keywords = {
  btn: {
    save: '保存',
    create: '作成',
    update: '更新'
  },
  nav: {
    accountresearch: 'アカウントリサーチ',
    insightlist: 'インサイトリスト',
    campaignlist: 'キャンペーンリスト',
    keyaccount: 'キーアカウント調査',
    accademy: 'アカデミー',
    plan: '利用プラン',
    support: 'よくある質問',
    question: 'お問合せ',
    logout: 'ログアウト',
    user: {
      create: '新規作成',
      list: 'ユーザーリスト',
      setting: 'プラン設定',
    }
  },
  caption: {
    search: '検索',
    clearall: '削除',
    clear: 'クリア', 
    instagram: 'Instagram',
    youtube: 'Youtube',
    tiktok: 'TikTok',
    followers: 'フォロワー数',
    follower: 'フォロワー',
    influencerlocation: '地域',
    gender: '性別',
    interestcare: '興味',
    interest: '興味',
    language: '言語',
    post: '最終投稿',
    engagement: 'エンゲージメント',
    contractinfo: 'コンタクト',
    bio: 'Bio',
    keyword: 'キーワード',
    hashtag: 'ハッシュタグ',
    audiencelocation: '地域',
    age: '年齢',
    subscriber: '加入者',
    averageview: '平均',
    sort: '整列',
    nextpage: 'Load',
    type: 'ジャンル',
  },
  label: {
    searchfromsite: 'Instagram・YouTube・TikTokからアカウントを探します。',
    influencersaved: 'アクント登録に成功しました。',
  },
  communcation_errs: {
    e001: 'メールとかパスワードが違いです。',
    e002: 'トクンエラー',
    e005: 'データベーズ接続エラー',
    e009: '対応メッソドがありません',
    e010: '先に登録してください',
    e011: 'トクン時間が経過しました、再度登録してください',
    e020: '同じなキャンペーンが存在します',
    e030: 'アカウントがずでに存在します',
    e039: '処理途中にエラーが発生しました',
    e040: '同じなユーザーが存在します',
    e041: 'プランを先に設定してください',
  }
};

export default keywords;