const keywords = {
  btn: {
    save: '保存',
    create: '作成',
    update: '更新',
    register: '登録'
  },
  nav: {
    accountresearch: 'アカウントリサーチ',
    insightlist: 'インサイトリスト',
    campaignlist: 'キャンペーンリスト',
    keyaccount: 'キーアカウント調査',
    academy: 'アカデミー',
    plan: '利用プラン',
    support: 'よくある質問',
    question: 'ヘルプセンター',
    logout: 'ログアウト',
    user: {
      create: '新規作成',
      list: 'ユーザーリスト',
      setting: 'プラン設定',
    }
  },
  caption: {
    search: '検索',
    clearall: '削除',
    clear: 'クリア', 
    instagram: 'Instagram',
    youtube: 'Youtube',
    tiktok: 'TikTok',
    followers: 'フォロワー数',
    follower: 'フォロワー',
    influencerlocation: '地域',
    gender: '性別',
    interestcare: '興味',
    interest: '興味',
    language: '言語',
    post: '最終投稿',
    engagement: 'エンゲージメント',
    contractinfo: 'コンタクト',
    bio: 'Bio',
    keyword: 'キーワード',
    hashtag: 'ハッシュタグエンゲージメント',
    audiencelocation: '地域',
    age: '年齢',
    subscriber: '登録者数',
    averageview: '平均再生回数',
    sort: '整列',
    nextpage: 'Load',
    type: 'ジャンル',
    engagement_tip: 'エンゲージメント率は「(いいね＋コメント)÷フォロワー」で算出しています。Instagramの平均エンゲージメント率は2%です。',
    bio_tip: 'bio description内のキーワードでインフルエンサーを特定します。',
    keyword_tip: 'インフルエンサ―に関連するトピックを検索します。簡単な単語での検索がおすすめです。',
    hashtag_tip: 'どのハッシュタグをつけた際の投稿が、フォロワーからリアクションされているか。',
    other_tip: '最適なインフルエンサーを絞り込むためには、まずはデフォルトのパーセンテージから初めて、徐々にパーセンテージを変更することをおすすめします。',
  },
  label: {
    searchfromsite: 'Instagram・YouTube・TikTokからアカウントを探します。',
    influencersaved: 'アカウントを登録しました。',
  },
  communcation_errs: {
    e001: 'メールアドレスが存在しません。',
    e002: 'トクンエラー。',
    e003: 'パスワードが違いです。',
    e005: 'データベーズ接続エラー。',
    e009: '対応メッソドがありません。',
    e010: '先に登録してください。',
    e011: 'トクン時間が経過しました、再度登録してください。',
    e020: 'このキャンペーン名は既に使われています。',
    e030: 'アカウントがずでに存在します。',
    e039: '処理途中にエラーが発生しました。',
    e040: '同じメールアドレスが存在します。',
    e041: 'プランを先に設定してください。',
    e049: '処理道中にエーラは発生しました。',
  }
};

export default keywords;